version: 0.2

phases:
  install:
    commands:
      - echo Installing Apache Web Server
      - sudo yum install -y httpd  # Installs the Apache server
  build:
    commands:
      - echo Starting Apache server
      - httpd -k start  # Starts Apache server in the container-friendly way

artifacts:
  files:
    - '**/*'  # Include all files in the build output

