version: 0.2
phases:
  install:
    commands:
      - sudo yum install -y httpd
      - sudo systemctl start httpd
  build:
    commands:
      - echo "Building the web app"
artifacts:
  files:
    - '**/*'

